baseURL = "https://www.danieldway.com"
languageCode = "en-us"
title = "Daniel Way"
theme = "minimal"

[params]
    author = "Daniel Way"
    description = "Full-stack Software Developer"
    githubUsername = "danielway"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway"
    copyright = "&copy; All rights reserved."

# Navigation

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social

[[menu.icon]]
    url = "mailto:projects@danieldway.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/danielway"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/daniel-way-693868171"
    name = "linkedin"
    weight = 3
